import { Book, ReadingGoal, UserProfile } from './types';

export const mockUserProfile: UserProfile = {
  name: 'Kate Rosoy',
  email: 'katerosoy@gmail.com',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=120&h=120&q=80',
  favoriteGenres: ['Self-Improvement', 'Technology', 'Fiction', 'Philosophy'],
  joinedAt: '2026-01-15',
};

export const mockReadingGoal: ReadingGoal = {
  annualTarget: 24,
  annualCompleted: 14,
  monthlyPagesTarget: 800,
  monthlyPagesCompleted: 640,
  currentStreak: 18,
  longestStreak: 45,
  streakDates: [
    '2026-06-07', '2026-06-08', '2026-06-09', '2026-06-10', '2026-06-11',
    '2026-06-12', '2026-06-13', '2026-06-14', '2026-06-15', '2026-06-16',
    '2026-06-17', '2026-06-18', '2026-06-19', '2026-06-20', '2026-06-21',
    '2026-06-22', '2026-06-23', '2026-06-24'
  ],
  monthlyHistory: [
    { month: 'Jan', pagesRead: 720, booksCompleted: 2 },
    { month: 'Feb', pagesRead: 910, booksCompleted: 3 },
    { month: 'Mar', pagesRead: 600, booksCompleted: 1 },
    { month: 'Apr', pagesRead: 850, booksCompleted: 2 },
    { month: 'May', pagesRead: 1100, booksCompleted: 4 },
    { month: 'Jun', pagesRead: 640, booksCompleted: 2 },
  ]
};

export const mockBooks: Book[] = [
  {
    id: '1',
    title: 'Atomic Habits',
    author: 'James Clear',
    coverGradient: 'linear-gradient(135deg, #FF6B6B 0%, #FF8E53 100%)',
    coverTextColor: '#FFFFFF',
    status: 'reading',
    progress: 68,
    rating: 5,
    genre: 'Self-Improvement',
    shelf: 'Self-Improvement',
    pages: 320,
    pagesRead: 218,
    notesCount: 14,
    quotesCount: 8,
    aiSummary: 'Atomic Habits provides a practical framework for improving every day. James Clear reveals strategies to form good habits, break bad ones, and master tiny behaviors that lead to remarkable results. He argues that system design is far more critical than goal setting.',
    keyTakeaways: [
      'An atomic habit is a regular practice or routine that is not only small and easy to do but is also the source of incredible power.',
      'If you want better results, then forget about setting goals. Focus on your system instead.',
      'The ultimate form of intrinsic motivation is when a habit becomes part of your identity.',
      'Four Laws of Behavior Change: Make it obvious, make it attractive, make it easy, make it satisfying.'
    ],
    reviewDue: true,
    dateStarted: '2026-06-10',
    isFavorite: true,
    notes: [
      { id: 'n1', content: 'Focus on 1% better every day. Compounding is incredibly powerful over months and years.', page: 15, createdAt: '2026-06-11T14:30:00Z' },
      { id: 'n2', content: 'Environments matter more than willpower. Rearrange items in your room to make positive habits effortless.', page: 85, createdAt: '2026-06-15T09:12:00Z' },
      { id: 'n3', content: 'Habit tracking creates a visual cue. Never miss twice. If you miss one day, get back on track immediately.', page: 194, createdAt: '2026-06-20T21:40:00Z' }
    ],
    quotes: [
      { id: 'q1', content: 'You do not rise to the level of your goals. You fall to the level of your systems.', page: 28, createdAt: '2026-06-11T14:35:00Z' },
      { id: 'q2', content: 'Every action you take is a vote for the type of person you wish to become.', page: 34, createdAt: '2026-06-12T10:05:00Z' }
    ],
    reviewCards: [
      { id: 'rc1', question: 'What are the Four Laws of Behavior Change?', answer: '1. Make it obvious. 2. Make it attractive. 3. Make it easy. 4. Make it satisfying.', easeFactor: 2.5, intervalDays: 3, repetitions: 1, nextReviewDate: '2026-06-25T12:00:00Z' },
      { id: 'rc2', question: 'Why does James Clear argue systems are superior to goals?', answer: 'Goals define the results you want to achieve, but systems are the processes that lead to those results. Winners and losers share the same goals; it is the systems that separate them.', easeFactor: 2.6, intervalDays: 4, repetitions: 1, nextReviewDate: '2026-06-25T12:00:00Z' }
    ]
  },
  {
    id: '2',
    title: 'Zero to One',
    author: 'Peter Thiel',
    coverGradient: 'linear-gradient(135deg, #111827 0%, #374151 100%)',
    coverTextColor: '#EDE3D2',
    status: 'reading',
    progress: 45,
    rating: 4,
    genre: 'Business',
    shelf: 'Business',
    pages: 224,
    pagesRead: 101,
    notesCount: 8,
    quotesCount: 4,
    aiSummary: 'Zero to One explores how to create singular, highly profitable monopolies that bring entirely new value to the world (going from 0 to 1), rather than copying existing formulas (going from 1 to n). Thiel advocates for vertical progress and technology-first cultures.',
    keyTakeaways: [
      'Monopolies drive innovation because they have the financial freedom to care about things other than survival.',
      'The contrarian question: What important truth do very few people agree with you on?',
      'If you want to create and capture durable value, do not build an undifferentiated commodity business.',
      'Sales and distribution are just as important as the product itself. Good engineering is not enough.'
    ],
    reviewDue: false,
    dateStarted: '2026-06-18',
    isFavorite: true,
    notes: [
      { id: 'n4', content: 'Monopolies are good for progress. Perfect competition eliminates all profit margins, leaving zero surplus for long-term R&D.', page: 34, createdAt: '2026-06-19T11:00:00Z' },
      { id: 'n5', content: 'The Last Mover Advantage: Be the last great mover in your market to enjoy decades of monopoly profits.', page: 58, createdAt: '2026-06-22T17:30:00Z' }
    ],
    quotes: [
      { id: 'q3', content: 'What important truth do very few people agree with you on?', page: 7, createdAt: '2026-06-18T22:15:00Z' },
      { id: 'q4', content: 'All happy families are alike; each unhappy family is unhappy in its own way. In business, the exact opposite is true.', page: 21, createdAt: '2026-06-19T11:05:00Z' }
    ],
    reviewCards: [
      { id: 'rc3', question: 'What is the distinction between vertical and horizontal progress?', answer: 'Horizontal progress is going from 1 to n (copying what works). Vertical progress is going from 0 to 1 (doing something nobody has done before).', easeFactor: 2.5, intervalDays: 1, repetitions: 0, nextReviewDate: '2026-06-26T12:00:00Z' }
    ]
  },
  {
    id: '3',
    title: 'The Creative Act',
    author: 'Rick Rubin',
    coverGradient: 'linear-gradient(135deg, #1C1916 0%, #7A5C3E 100%)',
    coverTextColor: '#FFFDF8',
    status: 'reading',
    progress: 15,
    rating: 0,
    genre: 'Art & Philosophy',
    shelf: 'Spiritual',
    pages: 432,
    pagesRead: 65,
    notesCount: 5,
    quotesCount: 7,
    aiSummary: 'Rick Rubin outlines a highly spiritual, meditative, and organic philosophy of creativity. He suggests that being an artist is not about the end product, but about a state of being and paying absolute attention to the universe.',
    keyTakeaways: [
      'The universe is a constant source of creative signals; an artist is simply a finely tuned antenna.',
      'Rules are assumptions about what is possible. They are not absolute truths, and can be broken to create magic.',
      'The goal is not to produce art for the market, but to express your own inner truth as sincerely as possible.',
      'Self-doubt is a natural shadow of the creative process, but it should never paralyze play.'
    ],
    reviewDue: true,
    dateStarted: '2026-06-22',
    isFavorite: false,
    notes: [
      { id: 'n6', content: 'Creativity is a relationship with the world. Keep your senses wide open, pay close attention to tiny changes around you.', page: 12, createdAt: '2026-06-23T08:00:00Z' }
    ],
    quotes: [
      { id: 'q5', content: 'To live as an artist is a way of being in the world. A way of perceiving. A practice of paying attention.', page: 3, createdAt: '2026-06-22T19:00:00Z' },
      { id: 'q6', content: 'The power of a vessel is in its emptiness.', page: 44, createdAt: '2026-06-23T08:15:00Z' }
    ],
    reviewCards: [
      { id: 'rc4', question: 'How does Rick Rubin define rules in creative work?', answer: 'Rules are limits that previous artists established. They are helpful starting points but dangerous constraints if accepted as absolute laws.', easeFactor: 2.4, intervalDays: 2, repetitions: 1, nextReviewDate: '2026-06-24T12:00:00Z' }
    ]
  },
  {
    id: '4',
    title: 'Sapiens',
    author: 'Yuval Noah Harari',
    coverGradient: 'linear-gradient(135deg, #3B2E2A 0%, #8D6E63 100%)',
    coverTextColor: '#FFFDF8',
    status: 'finished',
    progress: 100,
    rating: 5,
    genre: 'History',
    shelf: 'Technology',
    pages: 512,
    pagesRead: 512,
    notesCount: 19,
    quotesCount: 11,
    aiSummary: 'Sapiens covers the grand sweep of human history, from the emergence of Homo sapiens in East Africa to modern genetic engineering. Harari argues that Sapiens conquered the world through their unique capacity to believe in shared, imaginary myths like money, religion, and human rights.',
    keyTakeaways: [
      'Cognitive Revolution enabled Sapiens to talk about fictional entities, allowing large-scale flexible cooperation.',
      'Agricultural Revolution was history’s biggest fraud, leading to worse diets, longer hours, and massive inequality for individual farmers.',
      'Money is the ultimate inter-subjective trust system ever devised, transcending cultural, religious, and geographic divides.',
      'Modern scientific research is driven by empires and capitalism, seeking power, growth, and continuous return.'
    ],
    reviewDue: false,
    dateStarted: '2026-05-01',
    dateFinished: '2026-05-28',
    isFavorite: true,
    notes: [],
    quotes: [],
    reviewCards: []
  },
  {
    id: '5',
    title: 'The Pragmatic Programmer',
    author: 'Andy Hunt & Dave Thomas',
    coverGradient: 'linear-gradient(135deg, #1E3A8A 0%, #3B82F6 100%)',
    coverTextColor: '#FFFFFF',
    status: 'finished',
    progress: 100,
    rating: 5,
    genre: 'Technology',
    shelf: 'Technology',
    pages: 352,
    pagesRead: 352,
    notesCount: 12,
    quotesCount: 6,
    aiSummary: 'A timeless software engineering classic. It emphasizes personal responsibility, continuous learning, robust system architecture, and defensive coding practices. It provides actionable advice on keeping code DRY, modular, and easy to refactor.',
    keyTakeaways: [
      'Take responsibility for your mistakes and your career. Don’t offer excuses; provide options.',
      'DRY: Don’t Repeat Yourself. Every piece of knowledge must have a single, unambiguous, authoritative representation.',
      'Keep your code decoupled. Use orthgonality to ensure changes in one system do not impact unrelated ones.',
      'Prototype to learn. Don’t commit to production architecture until you have validated assumptions.'
    ],
    reviewDue: false,
    dateStarted: '2026-04-10',
    dateFinished: '2026-05-05',
    isFavorite: false,
    notes: [],
    quotes: [],
    reviewCards: []
  },
  {
    id: '6',
    title: 'Thinking, Fast and Slow',
    author: 'Daniel Kahneman',
    coverGradient: 'linear-gradient(135deg, #374151 0%, #111827 100%)',
    coverTextColor: '#EDE3D2',
    status: 'tbr',
    progress: 0,
    rating: 0,
    genre: 'Psychology',
    shelf: 'TBR',
    pages: 499,
    pagesRead: 0,
    notesCount: 0,
    quotesCount: 0,
    aiSummary: 'Daniel Kahneman, recipient of the Nobel Prize in Economic Sciences, presents a groundbreaking map of the human mind. He divides thinking into two systems: System 1 (fast, intuitive, emotional, unconscious) and System 2 (slow, deliberate, analytical, conscious).',
    keyTakeaways: [
      'System 1 operates automatically and quickly, with little or no effort and no sense of voluntary control.',
      'System 2 allocates attention to the effortful mental activities that demand it, including complex calculations.',
      'We are susceptible to cognitive biases (anchoring, availability heuristic, loss aversion) because our minds prefer System 1 over System 2 to save energy.',
      'Loss aversion: The pain of losing is psychologically about twice as powerful as the pleasure of gaining.'
    ],
    reviewDue: false,
    isFavorite: false,
    notes: [],
    quotes: [],
    reviewCards: []
  },
  {
    id: '7',
    title: 'Deep Work',
    author: 'Cal Newport',
    coverGradient: 'linear-gradient(135deg, #7F1D1D 0%, #B91C1C 100%)',
    coverTextColor: '#FFFFFF',
    status: 'finished',
    progress: 100,
    rating: 4,
    genre: 'Self-Improvement',
    shelf: 'Self-Improvement',
    pages: 304,
    pagesRead: 304,
    notesCount: 15,
    quotesCount: 8,
    aiSummary: 'Cal Newport argues that the ability to concentrate deeply on demanding tasks without distraction is a rare and highly valuable superpower in the modern information economy. He provides four practical rules to cultivate a deep work habit.',
    keyTakeaways: [
      'Deep Work: Professional activities performed in a state of distraction-free concentration that push your cognitive capabilities to their limit.',
      'Shallow Work: Noncognitively demanding, logistical-style tasks, often performed while distracted. These efforts tend to not create much new value.',
      'The Deep Work Hypothesis: The ability to perform deep work is becoming increasingly rare at exactly the same time that it is becoming increasingly valuable.',
      'Rule 1: Work Deeply; Rule 2: Embrace Boredom; Rule 3: Quit Social Media; Rule 4: Drain the Shallows.'
    ],
    reviewDue: true,
    dateStarted: '2026-05-10',
    dateFinished: '2026-06-02',
    isFavorite: true,
    notes: [
      { id: 'nd1', content: 'Attention residue is real. If you quickly check email, you lose focus on your main task for up to 20 minutes.', page: 44, createdAt: '2026-05-12T10:00:00Z' },
      { id: 'nd2', content: 'Establish a shut-down ritual to clear your working memory at the end of every day.', page: 120, createdAt: '2026-05-20T17:00:00Z' }
    ],
    quotes: [
      { id: 'qd1', content: 'If you don’t produce, you won’t thrive—no matter how skilled or talented you are.', page: 32, createdAt: '2026-05-12T10:15:00Z' }
    ],
    reviewCards: []
  },
  {
    id: '8',
    title: 'The Almanack of Naval Ravikant',
    author: 'Eric Jorgenson',
    coverGradient: 'linear-gradient(135deg, #0D9488 0%, #0F766E 100%)',
    coverTextColor: '#FFFFFF',
    status: 'finished',
    progress: 100,
    rating: 5,
    genre: 'Philosophy',
    shelf: 'Favorites',
    pages: 244,
    pagesRead: 244,
    notesCount: 22,
    quotesCount: 15,
    aiSummary: 'A curated compilation of wisdom, aphorisms, and insights on wealth, happiness, and peace shared by philosopher-investor Naval Ravikant. It advocates for specific knowledge, infinite leverage, and mindfulness.',
    keyTakeaways: [
      'Seek wealth, not money or status. Wealth is having assets that earn while you sleep.',
      'You will not get rich renting out your time. You must own equity to gain financial freedom.',
      'Understand the power of code and media. These are permissionless leverages that scale infinitely without costs.',
      'Specific knowledge is the knowledge you cannot be trained for. It is found by pursuing your genuine curiosity.'
    ],
    reviewDue: false,
    dateStarted: '2026-05-15',
    dateFinished: '2026-06-05',
    isFavorite: true,
    notes: [],
    quotes: [],
    reviewCards: []
  },
  {
    id: '9',
    title: 'Designing Data-Intensive Applications',
    author: 'Martin Kleppmann',
    coverGradient: 'linear-gradient(135deg, #1E1B4B 0%, #312E81 100%)',
    coverTextColor: '#FFFFFF',
    status: 'tbr',
    progress: 0,
    rating: 0,
    genre: 'Technology',
    shelf: 'TBR',
    pages: 616,
    pagesRead: 0,
    notesCount: 0,
    quotesCount: 0,
    aiSummary: 'A comprehensive, deep-dive guide into the architectures, tradeoffs, and designs of modern database systems, distributed networks, stream processors, and storage engines.',
    keyTakeaways: [
      'Reliability: The system should continue to function correctly even when things go wrong (fault-tolerance).',
      'Scalability: The ability of a system to cope with increased load by adding resources.',
      'Maintainability: Over time, many different people will work on the system. It should be easy to modify and understand.',
      'The difference between SQL (relational) and NoSQL (document-oriented or graph-based) models.'
    ],
    reviewDue: false,
    isFavorite: false,
    notes: [],
    quotes: [],
    reviewCards: []
  },
  {
    id: '10',
    title: 'Meditations',
    author: 'Marcus Aurelius',
    coverGradient: 'linear-gradient(135deg, #78350F 0%, #451A03 100%)',
    coverTextColor: '#FFFDF8',
    status: 'finished',
    progress: 100,
    rating: 5,
    genre: 'Philosophy',
    shelf: 'Favorites',
    pages: 256,
    pagesRead: 256,
    notesCount: 16,
    quotesCount: 12,
    aiSummary: 'The private stoic journal of Roman Emperor Marcus Aurelius. He reflects on self-discipline, mortality, duty, and emotional resilience under pressure, reminding himself that we cannot control outer events, only our reaction to them.',
    keyTakeaways: [
      'You have power over your mind - not outside events. Realize this, and you will find strength.',
      'The happiness of your life depends upon the quality of your thoughts.',
      'Our actions may be impeded, but there can be no impeding our intentions or dispositions.',
      'Waste no more time arguing about what a good man should be. Be one.'
    ],
    reviewDue: true,
    dateStarted: '2026-04-15',
    dateFinished: '2026-05-12',
    isFavorite: true,
    notes: [
      { id: 'nm1', content: 'Focus on the present moment. Do not worry about the future or despair over the past.', page: 22, createdAt: '2026-04-16T08:00:00Z' }
    ],
    quotes: [
      { id: 'qm1', content: 'The impediment to action advances action. What stands in the way becomes the way.', page: 65, createdAt: '2026-04-20T09:00:00Z' }
    ],
    reviewCards: []
  },
  // Remaining 14 books to complete the 24 books mock dataset
  {
    id: '11',
    title: 'The Lean Startup',
    author: 'Eric Ries',
    coverGradient: 'linear-gradient(135deg, #0369A1 0%, #0284C7 100%)',
    coverTextColor: '#FFFFFF',
    status: 'finished',
    progress: 100,
    rating: 4,
    genre: 'Business',
    shelf: 'Business',
    pages: 336,
    pagesRead: 336,
    notesCount: 4,
    quotesCount: 2,
    aiSummary: 'A methodology for creating startups through rapid scientific experimentation, validated learning, and iterative product releases (Build-Measure-Learn loops).',
    keyTakeaways: ['Validated learning is the key metric of progress for startups.', 'Create an MVP (Minimum Viable Product) to start learning immediately.'],
    reviewDue: false,
    dateStarted: '2026-03-01',
    dateFinished: '2026-03-20',
    isFavorite: false,
    notes: [],
    quotes: [],
    reviewCards: []
  },
  {
    id: '12',
    title: 'Show Your Work!',
    author: 'Austin Kleon',
    coverGradient: 'linear-gradient(135deg, #EAB308 0%, #CA8A04 100%)',
    coverTextColor: '#1F1A17',
    status: 'finished',
    progress: 100,
    rating: 4,
    genre: 'Art & Philosophy',
    shelf: 'Self-Improvement',
    pages: 224,
    pagesRead: 224,
    notesCount: 6,
    quotesCount: 5,
    aiSummary: 'A guide to sharing your creativity, letting people find you, and documenting your process online rather than hoarding your work.',
    keyTakeaways: ['Think process, not product. Share your daily struggles and insights.', 'Become a documentarian of what you do. Create a community around your curiosity.'],
    reviewDue: false,
    dateStarted: '2026-05-25',
    dateFinished: '2026-06-03',
    isFavorite: false,
    notes: [],
    quotes: [],
    reviewCards: []
  },
  {
    id: '13',
    title: 'High Output Management',
    author: 'Andrew S. Grove',
    coverGradient: 'linear-gradient(135deg, #1F2937 0%, #4B5563 100%)',
    coverTextColor: '#FFFFFF',
    status: 'tbr',
    progress: 0,
    rating: 0,
    genre: 'Business',
    shelf: 'TBR',
    pages: 272,
    pagesRead: 0,
    notesCount: 0,
    quotesCount: 0,
    aiSummary: 'The legendary former CEO of Intel teaches managers how to run organizations efficiently. He introduces OKRs and shows that the output of a manager is the output of the organizational units under their supervision.',
    keyTakeaways: ['A manager’s output is the output of their team.', 'Leverage is the measure of the output generated by a specific management activity.'],
    reviewDue: false,
    isFavorite: false,
    notes: [],
    quotes: [],
    reviewCards: []
  },
  {
    id: '14',
    title: 'Man’s Search for Meaning',
    author: 'Viktor E. Frankl',
    coverGradient: 'linear-gradient(135deg, #1C1916 0%, #292524 100%)',
    coverTextColor: '#EDE3D2',
    status: 'finished',
    progress: 100,
    rating: 5,
    genre: 'Philosophy',
    shelf: 'Favorites',
    pages: 184,
    pagesRead: 184,
    notesCount: 11,
    quotesCount: 8,
    aiSummary: 'Psychiatrist Viktor Frankl describes his experiences in Nazi concentration camps, developing Logotherapy—the philosophy that human drive is not powered by pleasure or power, but by the pursuit of meaning.',
    keyTakeaways: ['He who has a why to live can bear almost any how.', 'Everything can be taken from a man but one thing: the last of human freedoms—to choose one’s attitude.'],
    reviewDue: false,
    dateStarted: '2026-03-25',
    dateFinished: '2026-04-05',
    isFavorite: true,
    notes: [],
    quotes: [],
    reviewCards: []
  },
  {
    id: '15',
    title: 'Start with Why',
    author: 'Simon Sinek',
    coverGradient: 'linear-gradient(135deg, #BE123C 0%, #9F1239 100%)',
    coverTextColor: '#FFFFFF',
    status: 'tbr',
    progress: 0,
    rating: 0,
    genre: 'Business',
    shelf: 'TBR',
    pages: 256,
    pagesRead: 0,
    notesCount: 0,
    quotesCount: 0,
    aiSummary: 'Simon Sinek shows that the most influential leaders and companies inspire action by starting with WHY (purpose or belief), rather than WHAT they do or HOW they do it.',
    keyTakeaways: ['People don’t buy what you do; they buy why you do it.', 'The Golden Circle: Why, How, What.'],
    reviewDue: false,
    isFavorite: false,
    notes: [],
    quotes: [],
    reviewCards: []
  },
  {
    id: '16',
    title: 'Clean Code',
    author: 'Robert C. Martin',
    coverGradient: 'linear-gradient(135deg, #0284C7 0%, #1E40AF 100%)',
    coverTextColor: '#FFFFFF',
    status: 'finished',
    progress: 100,
    rating: 4,
    genre: 'Technology',
    shelf: 'Technology',
    pages: 464,
    pagesRead: 464,
    notesCount: 14,
    quotesCount: 3,
    aiSummary: 'A guide to software craftsmanship, presenting principles, patterns, and practices of writing clean, maintainable, readable code.',
    keyTakeaways: ['The only truly valid measurement of code quality is WTFs/minute.', 'Leave the campground cleaner than you found it.'],
    reviewDue: false,
    dateStarted: '2026-02-01',
    dateFinished: '2026-03-01',
    isFavorite: false,
    notes: [],
    quotes: [],
    reviewCards: []
  },
  {
    id: '17',
    title: 'Steal Like an Artist',
    author: 'Austin Kleon',
    coverGradient: 'linear-gradient(135deg, #1F2937 0%, #D97706 100%)',
    coverTextColor: '#FFFDF8',
    status: 'finished',
    progress: 100,
    rating: 5,
    genre: 'Art & Philosophy',
    shelf: 'Favorites',
    pages: 160,
    pagesRead: 160,
    notesCount: 5,
    quotesCount: 8,
    aiSummary: 'A manifesto for creativity in the digital age, explaining that nothing is entirely original. All art is built on what came before.',
    keyTakeaways: ['Immature poets imitate; mature poets steal.', 'Don’t wait until you know who you are to get started. Just make things.'],
    reviewDue: false,
    dateStarted: '2026-06-01',
    dateFinished: '2026-06-05',
    isFavorite: true,
    notes: [],
    quotes: [],
    reviewCards: []
  },
  {
    id: '18',
    title: 'Company of One',
    author: 'Paul Jarvis',
    coverGradient: 'linear-gradient(135deg, #4F46E5 0%, #312E81 100%)',
    coverTextColor: '#FFFFFF',
    status: 'tbr',
    progress: 0,
    rating: 0,
    genre: 'Business',
    shelf: 'TBR',
    pages: 272,
    pagesRead: 0,
    notesCount: 0,
    quotesCount: 0,
    aiSummary: 'An argument for why staying small can be a strategic business choice. It emphasizes stability, self-reliance, and control over endless scaling and VC-funded growth.',
    keyTakeaways: ['The goal should be to make your business better, not bigger.', 'Growth isn’t always the correct solution to business hurdles.'],
    reviewDue: false,
    isFavorite: false,
    notes: [],
    quotes: [],
    reviewCards: []
  },
  {
    id: '19',
    title: 'Dune',
    author: 'Frank Herbert',
    coverGradient: 'linear-gradient(135deg, #C2410C 0%, #7C2D12 100%)',
    coverTextColor: '#FFEDD5',
    status: 'tbr',
    progress: 0,
    rating: 0,
    genre: 'Fiction',
    shelf: 'Fiction',
    pages: 617,
    pagesRead: 0,
    notesCount: 0,
    quotesCount: 0,
    aiSummary: 'The masterpiece sci-fi epic set in the far future amidst a feudal interstellar empire. It details the coming-of-age of Paul Atreides on Arrakis, the desert planet.',
    keyTakeaways: ['Fear is the mind-killer. Fear is the little-death that brings total obliteration.', 'He who controls the spice controls the universe.'],
    reviewDue: false,
    isFavorite: false,
    notes: [],
    quotes: [],
    reviewCards: []
  },
  {
    id: '20',
    title: 'The War of Art',
    author: 'Steven Pressfield',
    coverGradient: 'linear-gradient(135deg, #B45309 0%, #78350F 100%)',
    coverTextColor: '#FFFFFF',
    status: 'finished',
    progress: 100,
    rating: 5,
    genre: 'Art & Philosophy',
    shelf: 'Favorites',
    pages: 192,
    pagesRead: 192,
    notesCount: 8,
    quotesCount: 6,
    aiSummary: 'A tough-love examination of the psychological barriers that prevent creative expression, defining this force as "Resistance". It provides a rallying cry to overcome fear and turn professional.',
    keyTakeaways: ['Resistance is the active, malicious force that sabotages your creative projects.', 'The professional shows up every single day, regardless of mood or block.'],
    reviewDue: false,
    dateStarted: '2026-05-18',
    dateFinished: '2026-05-24',
    isFavorite: true,
    notes: [],
    quotes: [],
    reviewCards: []
  },
  {
    id: '21',
    title: 'Good to Great',
    author: 'Jim Collins',
    coverGradient: 'linear-gradient(135deg, #991B1B 0%, #450A0A 100%)',
    coverTextColor: '#FFFFFF',
    status: 'finished',
    progress: 100,
    rating: 4,
    genre: 'Business',
    shelf: 'Business',
    pages: 320,
    pagesRead: 320,
    notesCount: 3,
    quotesCount: 1,
    aiSummary: 'Jim Collins analyzes why average companies achieve breakout success while others stay mediocre. He introduces concepts like Level 5 Leadership, the Hedgehog Concept, and the Flywheel.',
    keyTakeaways: ['Good is the enemy of great.', 'Get the right people on the bus first, then figure out where to drive it.'],
    reviewDue: false,
    dateStarted: '2026-01-20',
    dateFinished: '2026-02-15',
    isFavorite: false,
    notes: [],
    quotes: [],
    reviewCards: []
  },
  {
    id: '22',
    title: 'Siddhartha',
    author: 'Hermann Hesse',
    coverGradient: 'linear-gradient(135deg, #0F766E 0%, #115E59 100%)',
    coverTextColor: '#FFFDF8',
    status: 'finished',
    progress: 100,
    rating: 5,
    genre: 'Fiction',
    shelf: 'Fiction',
    pages: 152,
    pagesRead: 152,
    notesCount: 7,
    quotesCount: 10,
    aiSummary: 'A poetic novel following Siddhartha on his spiritual journey of self-discovery during the time of Gautama Buddha. Siddhartha learns that wisdom cannot be taught; it must be lived.',
    keyTakeaways: ['Knowledge can be communicated, but not wisdom.', 'I can think, I can wait, I can fast.'],
    reviewDue: false,
    dateStarted: '2026-02-18',
    dateFinished: '2026-02-28',
    isFavorite: true,
    notes: [],
    quotes: [],
    reviewCards: []
  },
  {
    id: '23',
    title: 'Building a Second Brain',
    author: 'Tiago Forte',
    coverGradient: 'linear-gradient(135deg, #4338CA 0%, #312E81 100%)',
    coverTextColor: '#FFFFFF',
    status: 'finished',
    progress: 100,
    rating: 4,
    genre: 'Self-Improvement',
    shelf: 'Self-Improvement',
    pages: 272,
    pagesRead: 272,
    notesCount: 11,
    quotesCount: 5,
    aiSummary: 'A methodology for saving, organizing, and retrieving your ideas, bookmarks, notes, and professional assets using a structured digital notebook system (CODE system).',
    keyTakeaways: ['Capture what resonates, Organize by actionability, Distill the essence, Express your work.', 'Your brain is for having ideas, not for holding them.'],
    reviewDue: false,
    dateStarted: '2026-03-10',
    dateFinished: '2026-03-29',
    isFavorite: false,
    notes: [],
    quotes: [],
    reviewCards: []
  },
  {
    id: '24',
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    coverGradient: 'linear-gradient(135deg, #1E1B4B 0%, #4C1D95 100%)',
    coverTextColor: '#EDE3D2',
    status: 'tbr',
    progress: 0,
    rating: 0,
    genre: 'Fiction',
    shelf: 'TBR',
    pages: 180,
    pagesRead: 0,
    notesCount: 0,
    quotesCount: 0,
    aiSummary: 'The classic American novel documenting Nick Carraway’s encounters with the mysterious millionaire Jay Gatsby on Long Island during the Roaring Twenties.',
    keyTakeaways: ['So we beat on, boats against the current, borne back ceaselessly into the past.'],
    reviewDue: false,
    isFavorite: false,
    notes: [],
    quotes: [],
    reviewCards: []
  }
];
